name = "Re:Create Public SMP"
author = "codeN"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "675a96aa14090def05df2204efadd5b171341cad0dd3e0a1f4471a514a2a9f81"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
