name = "Re:Create Public SMP"
author = "codeN"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cdc4d88532714de13fb4b0787866c6e18897653fc3968f8e98ae352b68d9d5e5"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
